package com.arduia.currency

val CURRENCY_CODE_COUNTRY_NAME = mapOf(
    "ALL" to "Albania Lek",
    "AFN" to "Afghanistan Afghani",
    "ARS" to "Argentina Peso",
    "AWG" to "Aruba Guilder",
    "AUD" to "Australia Dollar",
    "AZN" to "Azerbaijan New Manat",
    "BSD" to "Bahamas Dollar",
    "BBD" to "Barbados Dollar",
    "BDT" to "Bangladeshi taka",
    "BYR" to "Belarus Ruble",
    "BZD" to "Belize Dollar",
    "BMD" to "Bermuda Dollar",
    "BOB" to "Bolivia Boliviano",
    "BAM" to "Bosnia and Herzegovina Convertible Marka",
    "BWP" to "Botswana Pula",
    "BGN" to "Bulgaria Lev",
    "BRL" to "Brazil Real",
    "BND" to "Brunei Darussalam Dollar",
    "KHR" to "Cambodia Riel",
    "CAD" to "Canada Dollar",
    "KYD" to "Cayman Islands Dollar",
    "CLP" to "Chile Peso",
    "CNY" to "China Yuan Renminbi",
    "COP" to "Colombia Peso",
    "CRC" to "Costa Rica Colon",
    "HRK" to "Croatia Kuna",
    "CUP" to "Cuba Peso",
    "CZK" to "Czech Republic Koruna",
    "DKK" to "Denmark Krone",
    "DOP" to "Dominican Republic Peso",
    "XCD" to "East Caribbean Dollar",
    "EGP" to "Egypt Pound",
    "SVC" to "El Salvador Colon",
    "EUR" to "Euro Member Countries",
    "FKP" to "Falkland Islands (Malvinas) Pound",
    "FJD" to "Fiji Dollar",
    "GHC" to "Ghana Cedis",
    "GIP" to "Gibraltar Pound",
    "GTQ" to "Guatemala Quetzal",
    "GGP" to "Guernsey Pound",
    "GYD" to "Guyana Dollar",
    "HNL" to "Honduras Lempira",
    "HKD" to "Hong Kong Dollar",
    "HUF" to "Hungary Forint",
    "ISK" to "Iceland Krona",
    "INR" to "India Rupee",
    "IDR" to "Indonesia Rupiah",
    "IRR" to "Iran Rial",
    "IMP" to "Isle of Man Pound",
    "ILS" to "Israel Shekel",
    "JMD" to "Jamaica Dollar",
    "JPY" to "Japan Yen",
    "JEP" to "Jersey Pound",
    "KZT" to "Kazakhstan Tenge",
    "KPW" to "Korea (North) Won",
    "KRW" to "Korea (South) Won",
    "KGS" to "Kyrgyzstan Som",
    "LAK" to "Laos Kip",
    "LBP" to "Lebanon Pound",
    "LRD" to "Liberia Dollar",
    "MKD" to "Macedonia Denar",
    "MYR" to "Malaysia Ringgit",
    "MUR" to "Mauritius Rupee",
    "MXN" to "Mexico Peso",
    "MNT" to "Mongolia Tughrik",
    "MMK" to "Myanmar",
    "MZN" to "Mozambique Metical",
    "NAD" to "Namibia Dollar",
    "NPR" to "Nepal Rupee",
    "ANG" to "Netherlands Antilles Guilder",
    "NZD" to "New Zealand Dollar",
    "NIO" to "Nicaragua Cordoba",
    "NGN" to "Nigeria Naira",
    "NOK" to "Norway Krone",
    "OMR" to "Oman Rial",
    "PKR" to "Pakistan Rupee",
    "PAB" to "Panama Balboa",
    "PYG" to "Paraguay Guarani",
    "PEN" to "Peru Nuevo Sol",
    "PHP" to "Philippines Peso",
    "PLN" to "Poland Zloty",
    "QAR" to "Qatar Riyal",
    "RON" to "Romania New Leu",
    "RUB" to "Russia Ruble",
    "SHP" to "Saint Helena Pound",
    "SAR" to "Saudi Arabia Riyal",
    "RSD" to "Serbia Dinar",
    "SCR" to "Seychelles Rupee",
    "SGD" to "Singapore Dollar",
    "SBD" to "Solomon Islands Dollar",
    "SOS" to "Somalia Shilling",
    "ZAR" to "South Africa Rand",
    "LKR" to "Sri Lanka Rupee",
    "SEK" to "Sweden Krona",
    "CHF" to "Switzerland Franc",
    "SRD" to "Suriname Dollar",
    "SYP" to "Syria Pound",
    "TWD" to "Taiwan New Dollar",
    "THB" to "Thailand Baht",
    "TTD" to "Trinidad and Tobago Dollar",
    "TRY" to "Turkey Lira",
    "TRL" to "Turkey Lira",
    "TVD" to "Tuvalu Dollar",
    "UAH" to "Ukraine Hryvna",
    "GBP" to "United Kingdom Pound",
    "UGX" to "Uganda Shilling",
    "USD" to "United States Dollar",
    "UYU" to "Uruguay Peso",
    "UZS" to "Uzbekistan Som",
    "VEF" to "Venezuela Bolivar",
    "VND" to "Viet Nam Dong",
    "YER" to "Yemen Rial",
    "ZWD" to "Zimbabwe Dollar"
)
